#!/usr/bin/env bash
# LanternFlyTVOS generation script
# Helper script that runs in a Raspbian/others chroot to create the LanternFlyTVOS distro
# Written by Tailor VJ

set -x
set -e

source /common.sh

unpack /filesystem/opt /opt
unpack /filesystem/boot /"${BASE_BOOT_MOUNT_PATH}"

# Update and install necessary packages
apt-get update

# Install a minimal desktop environment and necessary tools
apt-get install -y --no-install-recommends \
    xserver-xorg \
    xinit \
    lxde-core \
    lxterminal \
    lightdm \
    fbi \
    git \
    screen \
    avahi-daemon \
    xdotool \
    vim \
    expect \
    feh \
    wget \
    unzip

# Download the zip file
wget $LANTERNFLY_ZIP_URL -O /tmp/lanternflytv.zip

# Unzip the file
unzip /tmp/lanternflytv.zip -d /tmp/

# Install the .deb file
# apt install /tmp/lanternflytv_*.deb

# Clean up
rm /tmp/lanternflytv.zip
rm /tmp/lanternflytv_*.deb

# Cleanup
apt-get clean
apt-get autoremove -y
